-- iterativeflow bundled migration
-- Generated by scripts/generate-migrations.ts from src/storage/schema.ts.
-- Statements are post-processed with `IF NOT EXISTS` so re-applying is a no-op.

CREATE SCHEMA IF NOT EXISTS "workflow";
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."events" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"run_id" uuid NOT NULL,
	"type" text NOT NULL,
	"cursor_key" text,
	"payload" jsonb,
	"at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"parent_run_id" uuid,
	"parent_cursor_key" text,
	"input" jsonb NOT NULL,
	"output" jsonb,
	"error" jsonb,
	"attempts" integer DEFAULT 0 NOT NULL,
	"idempotency_key" text,
	"tags" text[],
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."signals" (
	"run_id" uuid NOT NULL,
	"cursor_key" text NOT NULL,
	"delivered" boolean DEFAULT false NOT NULL,
	"payload" jsonb,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"delivered_at" timestamp with time zone,
	CONSTRAINT "signals_run_id_cursor_key_pk" PRIMARY KEY("run_id","cursor_key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."steps" (
	"run_id" uuid NOT NULL,
	"cursor_key" text NOT NULL,
	"status" text NOT NULL,
	"result" jsonb,
	"error" jsonb,
	"attempts" integer DEFAULT 0 NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "steps_run_id_cursor_key_pk" PRIMARY KEY("run_id","cursor_key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."timers" (
	"run_id" uuid NOT NULL,
	"cursor_key" text NOT NULL,
	"fire_at" timestamp with time zone NOT NULL,
	"fired_at" timestamp with time zone,
	CONSTRAINT "timers_run_id_cursor_key_pk" PRIMARY KEY("run_id","cursor_key")
);
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'workflow' AND table_name = 'events' AND constraint_name = 'events_run_id_runs_id_fk'
  ) THEN
    ALTER TABLE "workflow"."events" ADD CONSTRAINT "events_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "workflow"."runs"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'workflow' AND table_name = 'signals' AND constraint_name = 'signals_run_id_runs_id_fk'
  ) THEN
    ALTER TABLE "workflow"."signals" ADD CONSTRAINT "signals_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "workflow"."runs"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'workflow' AND table_name = 'steps' AND constraint_name = 'steps_run_id_runs_id_fk'
  ) THEN
    ALTER TABLE "workflow"."steps" ADD CONSTRAINT "steps_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "workflow"."runs"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'workflow' AND table_name = 'timers' AND constraint_name = 'timers_run_id_runs_id_fk'
  ) THEN
    ALTER TABLE "workflow"."timers" ADD CONSTRAINT "timers_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "workflow"."runs"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "flow_events_run_id_idx" ON "workflow"."events" USING btree ("run_id","at");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "flow_runs_idempotency_idx" ON "workflow"."runs" USING btree ("name","version","idempotency_key") WHERE "workflow"."runs"."idempotency_key" IS NOT NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "flow_runs_status_idx" ON "workflow"."runs" USING btree ("status","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "flow_runs_name_status_idx" ON "workflow"."runs" USING btree ("name","status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "flow_runs_reconciler_idx" ON "workflow"."runs" USING btree ("updated_at") WHERE "workflow"."runs"."status" IN ('pending', 'sleeping', 'awaiting_signal', 'retrying');
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "flow_runs_parent_idx" ON "workflow"."runs" USING btree ("parent_run_id") WHERE "workflow"."runs"."parent_run_id" IS NOT NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "flow_runs_tags_gin_idx" ON "workflow"."runs" USING gin ("tags");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "flow_timers_fire_at_idx" ON "workflow"."timers" USING btree ("fire_at") WHERE "workflow"."timers"."fired_at" IS NULL;
