#!/usr/bin/env tsx
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateDrizzleJson, generateMigration } from "drizzle-kit/api";
import * as schema from "../src/storage/schema";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const REPO = join(scriptDir, "..");
const OUT_DIR = join(REPO, "migrations");
const SNAP_DIR = join(OUT_DIR, "meta");

const wrapFk = (sql: string): string =>
  sql.replace(
    /^ALTER TABLE "([^"]+)"\."([^"]+)" ADD CONSTRAINT "([^"]+)" ([\s\S]*?);\s*$/m,
    (_match, sch, tbl, cn, rest) =>
      `DO $$ BEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints\n    WHERE constraint_schema = '${sch}' AND table_name = '${tbl}' AND constraint_name = '${cn}'\n  ) THEN\n    ALTER TABLE "${sch}"."${tbl}" ADD CONSTRAINT "${cn}" ${rest};\n  END IF;\nEND $$;`,
  );

const idempotent = (sql: string): string =>
  wrapFk(
    sql
      .replace(/^CREATE SCHEMA "/gm, 'CREATE SCHEMA IF NOT EXISTS "')
      .replace(/^CREATE TABLE "/gm, 'CREATE TABLE IF NOT EXISTS "')
      .replace(/^CREATE UNIQUE INDEX "/gm, 'CREATE UNIQUE INDEX IF NOT EXISTS "')
      .replace(/^CREATE INDEX "/gm, 'CREATE INDEX IF NOT EXISTS "'),
  );

const stableStringify = (v: unknown): string => JSON.stringify(v, null, 2);

// `generateDrizzleJson` stamps each snapshot with a fresh uuid `id` and the
// previous one's `prevId`. Strip them for content-equality comparison.
const fingerprint = (v: unknown): string => {
  const o = v as Record<string, unknown>;
  const { id: _id, prevId: _prev, ...rest } = o;
  return JSON.stringify(rest);
};

mkdirSync(OUT_DIR, { recursive: true });
mkdirSync(SNAP_DIR, { recursive: true });

const existingSnapshots = readdirSync(SNAP_DIR)
  .filter((f) => f.endsWith("_snapshot.json"))
  .sort();

const next = generateDrizzleJson(schema as unknown as Record<string, unknown>);

const previousFile = existingSnapshots.at(-1);
const previous = previousFile
  ? (JSON.parse(readFileSync(join(SNAP_DIR, previousFile), "utf8")) as Record<string, unknown>)
  : generateDrizzleJson({});

if (fingerprint(previous) === fingerprint(next)) {
  console.log("schema unchanged — no new migration written");
  process.exit(0);
}

const statements = await generateMigration(
  previous as unknown as Parameters<typeof generateMigration>[0],
  next,
);

const seq = String(existingSnapshots.length).padStart(4, "0");
const name =
  process.env.MIGRATION_NAME ?? (existingSnapshots.length === 0 ? "init" : `migration_${seq}`);
const filename = `${seq}_${name}.sql`;
const sqlPath = join(OUT_DIR, filename);

const header =
  "-- iterativeflow bundled migration\n" +
  "-- Generated by scripts/generate-migrations.ts from src/storage/schema.ts.\n" +
  "-- Statements are post-processed with `IF NOT EXISTS` so re-applying is a no-op.\n\n";

const body =
  statements
    .map((s) => idempotent(s.trim()))
    .filter((s) => s.length > 0)
    .join("\n--> statement-breakpoint\n") + "\n";

writeFileSync(sqlPath, header + body, "utf8");
writeFileSync(join(SNAP_DIR, `${seq}_snapshot.json`), stableStringify(next), "utf8");

console.log(`wrote ${filename} (${statements.length} statements)`);
console.log(`wrote meta/${seq}_snapshot.json`);
